import Head from 'next/head'
import {signIn, signOut, useSession} from "next-auth/react";

export default function Home() {
  const url = process.env.NEXT_PUBLIC_LINE_AUTH_REQUEST_URL

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={() => signIn("line")}>LINEログインする</button>
      </main>
    </>
  )
}
